
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cms
    username: nb_zzang
    password: nb1120
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false


jpa:
  show-sql: true
  database: postgresql
  hibernate:
    ddl-auto: update